### ISSUE TITLE
Can not run on Arclight

### ISSUE THREAD

**Issue by ahdg6** [K0bus/CreativeManager#10]
**Describe the bug**
CreativeManager can not run on Arclight.
I have reported to Arclight's author(https://github.com/IzzelAliz/Arclight/issues/349)
but they said it was caused by plugin side.

https://paste.ubuntu.com/p/9H4wkzg3Wd/

**Comment by K0bus** [comment]
Solved in new version by updating my own lib.

https://www.spigotmc.org/resources/%E2%9A%A1-creativemanager-%E2%9A%A1-customizable-complete-control.75097/update?update=417119
