### ISSUE TITLE
DROP ITEMS

### ISSUE THREAD

**Issue by kiskaserver** [K0bus/CreativeManager#11]
The player in the creative puts blocks such as:
Bed, picture, frame, boat, cart, armor rack.
Goes into survival mode and quietly gets these blocks when he breaks them.

 - PaperMC
 - Java 16
 - 1.15

- Xeno e2520v3 6/12
- 16 GB DDR4
- 240GB SSD/1 TB HDD

**Comment by K0bus** [comment]
Hi,
Yes i don't log entity anyway.
For bed i let your issue open for fixing it.
