### ISSUE TITLE
Items won't drop for GM0 player after upgrading to latest version

### ISSUE THREAD

**Issue by sphings79** [K0bus/CreativeManager#16]
**Describe the bug**
After upgrade to latest version naturally generated items for non op gm 0  players won't drop anymore.
If you are op vereything is fine. After unload the plugin items dropped fine for all players.

**To Reproduce**
Upgrade to latest version and mine a block

**Expected behavior**
block should drop

**Screenshots**

**Server informations:**
[10:40:17 INFO]: This server is running Paper version git-Paper-178 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 3109dd8)
Java 17
Your latest from Spigot

**Hardware information :**
- CPU
- 25GB for MC
- 800GB SSD

**Smartphone (please complete the following information):**
 - Version [e.g. 22

**Additional context**

**Comment by LilianLem** [comment]
I managed to fix that by granting creativemanager.bypass.log permission to everyone, which is supposed to allow players in survival mode to drop blocks placed in creative mode.

**Comment by sphings79** [comment]
The problem was that players were not able to mine blocks wich were NOT placed in creative.
Have not tried the latest version until now
