### ISSUE TITLE
Normal players (without access to creative) can break blocks inside WorldGuard protections

### ISSUE THREAD

**Issue by NicoNekoDev** [K0bus/CreativeManager#17]
**Describe the bug**
When using "custom items" plugins combining with WorldGuard (unsure if that combination is required) the players can break blocks in protected world guard regions and in the unprotected regions they don't get any items.

**To Reproduce**
1. Create a region with build/break/passtrough deny
2. De-op yourself or make it so you're also denied to build/break blocks in that region.
3. Break a block

**Expected behavior**
For the break to not work

**Screenshots**
https://media.discordapp.net/attachments/718516051092176988/938887728223899709/unknown.png
Here is me using the command `/wg debug testbreak <player>`

**Server informations:**
 - Spigot version (or another): Paper version git-Paper-182 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2ec04e0)
 - Java version: 17
 - Plugin version: 1.19.1

**Additional context**
They also don't get items when breaking blocks outside protected regions.
Here is the list of the plugins:
```
Plugins (107): AdvancedGiveaways, AdvancedReplay*, ajLeaderboards, AnotherDailyBonus, AntiCheatReplay, AsyncWorldEdit, AuctionGUIPlus, AuthMe, Bank, BeehivesPro, BetterRTP, BKCommonLib, ChatFeelings, ChestSort, Citizens, CitizensBooks, CleanMOTD, CMI, CMILib, Codex, ConditionalEvents, Core, CoreProtect, CraftingStore, DecentHolograms, DeluxeCombat, DeluxeCombat_Addon_WG*, DeluxeMenus, DeluxeSellwands, DiscordSRV, eco, EcoArmor, EcoEnchants, EcoEnchantsGUI, EcoItems, EcoSkills, EpicFurnaces, EpicHoppers, ExcellentCrates, ExecutableBlocks, ExecutableItems, FarmControl, GSit, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, InventorySaver, ItemEdit, Jobs, Karma, KiteBoard, LastLoginAPI, LevelledMobs, LibsDisguises, LiteBans, LocketteX, LuckPerms, Matrix, MineTweaks, MoreDispenserUtilities, My_Worlds, MythicMobs, NametagEdit, NBTAPI, NexEngine, Oh_the_dungeons_youll_go, OreAnnouncer, Parties, PlaceholderAPI, PlayerShopGUIPlus, Playtime, PlugManX (PlugMan), ProtectionStones, ProtocolFirewall, ProtocolLib, PunishGUI, Quests, Reforges, RoseStacker, RPGHorses, SCore, ShopGUIPlus, Shopkeepers, SkinsRestorer, Skulls, sleep-most, SlimeMap, SlotMachine, spark, StatTrackers, SuperbVote, SuperVanish, Talismans, TempFly, TigerReports, TradeSystem, UltimateAutoRestart, UltimateKits, UltimateTimber, Vault, ViewDistanceTweaks, VoidGen, Votifier, Vouchers, VTitleAuth, WorldEdit, WorldGuard
```
I did removed CreativeManager and everythings works fine.

**Comment by K0bus** [comment]
Hi thank for report fixed in 1.19.2.

https://www.spigotmc.org/resources/%E2%9A%A1-creativemanager-%E2%9A%A1-customizable-complete-control.75097/update?update=443586
