### ISSUE TITLE
One time use Items

### ISSUE THREAD

**Issue by mitchngwen** [K0bus/CreativeManager#19]
**Is your feature request related to a problem? Please describe.**
Being able to set some items to one time use would then allow you to make that item purchasable in an in game store. An example would be spawn eggs and spawners.

**Describe the solution you'd like**
A way to set in the config, items that have a one time use these items will not be allowed to be obtainable in the creative menu. The items in this config category would disappear after one use (spawn eggs) placable items would be removed from your inventory when placing them and would return to your inventory when breaking them.

**Describe alternatives you've considered**
I have considered having someone make a plugin with just this feature.

**Additional context**
This feature would greatly enhance any creative server by allowing server owners to make some items only obtainable through a store, event or mini game. etc.

**Comment by K0bus** [comment]
This would be a nice option but actually all protection added by CreativeManager can't allow to make that.
If you want these option i think you have to use a custom item creation like ExecutableItems or other plugins.
These plugins allow you to create an items that spawn an entity with a limited charge.
