### ISSUE TITLE
Transfering items from creative to survival

### ISSUE THREAD

**Issue by wellnesscookie** [K0bus/CreativeManager#25]
**Describe the bug**
Players can retrieve items from creative back to survival using campfire.
They take the campfire and any item from creative, put an item on campfire, go back to survival and take the item.

**To Reproduce**
1. Place campfire
2. Take item from creative
3. Place item on campfire while in creative 
4. Go back to survival
5. Take the item from campfire (there you have free items)

**Expected behavior**
Interaction disallowed with campfire

**Screenshots**
No need

**Server informations:**
 - Spigot version: 1.19.3
 - Java version: 17
 - Plugin version

**Hardware information :**
- CPU: i7
- RAM: 14 GB 
- Storage: SSD

**Comment by K0bus** [comment]
Hi,
This can be fixed by enable the useblock blacklist and add CAMPFIRE.
Can you tell me if it's good for you ?

**Comment by wellnesscookie** [comment]
Yes, we did fix it that way, but not before players had glitched items.
Is this plugin meant to come with some predefined protections as this one?

Or it does not come set up with anything at all? Just asking, not sure.
That works just well, but when all of these updates start coming, it's almost inevitable to forget about something as this campfire.

**Comment by K0bus** [comment]
I can check to add this protection directly in the container protection.

**Comment by wellnesscookie** [comment]
That would be lovely! Thanks for fast response!

**Comment by K0bus** [comment]
Added in the latest dev commit : 
https://github.com/K0bus/CreativeManager/commit/fb4f3ade006c365067ba00fb913e152ba8de8443
