### ISSUE TITLE
Events of priority monitor are getting modified

### ISSUE THREAD

**Issue by Thorinwasher** [K0bus/CreativeManager#30]
**Describe the bug**
An eventlistener of priority `MONITOR` should never modify the event. I found muliple instances where this was the case. Why does this matter? Because other plugins could also listen to the event at monitor priority. Modifying the event at the same priority means that there's a chance that those plugins recieve invalid input on what happened with the event.

**To Reproduce**
By looking into the code, I found this behavior in these following listeners:
- event.PlayerBreak
- event.PlayerInteractAtEntity
- event.PlayerInteractEntity

**Expected behavior**
Have those listeners be on a different priority

**Screenshots**
N/A

**Server information:**
 - N/A

**Hardware information :**
- N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by K0bus** [comment]
Fixed in #31
