### ISSUE TITLE
Shopkeepers compability

### ISSUE THREAD

**Issue by hero23550** [K0bus/CreativeManager#32]
**Describe the bug**
Enabling the container protection feature also doesn't allow me to change items in my admin shopkeeper made using https://www.spigotmc.org/resources/shopkeepers.80756/ btw it requires creative edit admin shopkeepers. I was hoping if you could detect this plugin in servers and stop the conflicts

**To Reproduce**
1. ... Install https://www.spigotmc.org/resources/%E2%9A%A1-creativemanager-%E2%9A%A1-customizable-complete-control.75097/
2. ... Install https://www.spigotmc.org/resources/shopkeepers.80756/
3. ... Install https://luckperms.net/
4. ... Create an admin shop using shopkeepers plugin
5. ... Deop your self and give perms for gamemode creative using luckperms
6. ... Make sure that Container protection is enabled in the config of CreativeManager
7. ... Shift-Right click the admin shopkeeper in creative to edit it

**Expected behavior**
admin Shopkeeper's editing gui should have normally opened

**Screenshots**
![image](https://github.com/K0bus/CreativeManager/assets/117738282/5d45a575-7215-46fe-bcaf-1bee6a550e64)

**Server information:**
 - git-Paper-493 (MC: 1.20.4)
 - Java version
 - 1.35.3

**Hardware information :**
- 2
- 2600
- 4gb

**Comment by K0bus** [comment]
Should be fixed here https://github.com/K0bus/CreativeManager/commit/5ce8d76d2eb9420a43de4647738bf82c714b68dc
What permission given to your admins ?

**Comment by hero23550** [comment]
![image](https://github.com/K0bus/CreativeManager/assets/117738282/370047a2-ffa4-4fec-bbeb-a07fcb93f7d3)
btw gui protection is off anyways

**Comment by hero23550** [comment]
btw here is the gui of admin shopkeeper
![shopkeepers-admin-shop-gui](https://github.com/K0bus/CreativeManager/assets/117738282/cae3ac35-3bd7-4f8a-832c-be88b4f3a6d4)

**Comment by K0bus** [comment]
For plugins gui permission need to add this : creativemanager.bypass.gui
Be care, this permission allow your group to open all custom gui inventory
