### ISSUE TITLE
Blocks are disappearing

### ISSUE THREAD

**Issue by mrdeniska1234** [K0bus/CreativeManager#36]
**Describe the bug**
After the explosion of blocks from those placed in the creative, they simply disappear

**To Reproduce**
1. Switch to /gm 1 and place any blocks on the ground.
2. Switch to /gm 0 and place dynamite.
3. Detonate the dynamite.

**Screenshots**
[Video](https://youtu.be/tjRxSvo5m2E)

**Expected behavior**
I expect that after the explosion, the blocks from creative mode will remain in place unchanged.

**Server information:**
 - Purpur 1.21.1 (build 2297)
 - Java 21
 - Plugin version 1.35.8

**Hardware information :**
 - Xeon E5-2689
 - 64GB
 - 4TB HDD

**Comment by potatoru** [comment]
I have the same issue

**Comment by potatoru** [comment]
Fixed in https://github.com/K0bus/CreativeManager/commit/a8117605b1aeee903c37a90ba9c5633520a66276
