### ISSUE TITLE
[FR] Lag

### ISSUE THREAD

**Issue by Bossbirdyman51** [K0bus/CreativeManager#5]
Bonjour,
J'utilise la dernière version du plugin qui est plutôt bien en soit je suis passé d'un autre à celui là sans soucis cepandant depuis quelque jours j'ai des lags assez énorme :
![image](https://user-images.githubusercontent.com/13882938/114569879-a8153180-9c75-11eb-968c-7681b282ed7c.png)

J'utilise la dernière version de paper.

Je vous remercie,

**Comment by K0bus** [comment]
Bonjour,
Toutes mes excuses pour les délais sur cette issue que je n'avais pas vu.
Pouvez vous me dire si l'incident perdure sur les dernières versions de CreativeManager ?
Si oui pouvez vous également me donner les spécifications de la machine hébergeant votre serveur.
Si le problème est bien persistant, vous pouvez désactiver temporairement la protection de loot, je doit travailler cette partie qui est la plus complexe du plugins pour permettre des sauvegarde asynchrone des logs permettant cette protection.

**Comment by K0bus** [comment]
Hello,
Ton sans retour de ta part, je pense que la dernière update doit régler ton problème #7
